on:
  push:
    branches:
      - master
  pull_request:

name: ci
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.14.x]
        platform: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Install Go
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout code
        uses: actions/checkout@v1
      - name: Build
        run: go build ./...
      - name: Test
        run: go test ./...
      - name: Run bench cfg Tool
        run: go run ./cmd/bench cfg true

  lint:
    strategy:
      matrix:
        go-version: [1.14.x]
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go-version }}
      - name: Configure Go Environment
        run: |
          echo ::set-env name=GOPATH::${{ runner.workspace }}
          echo ::add-path::${{ runner.workspace }}/bin
      - name: Go Environment
        run: go env
      - name: Checkout code
        uses: actions/checkout@v1
      - name: Bootstrap
        run: ./script/bootstrap.sh
      - name: Lint
        run: ./script/lint.sh
